services:
    Adsazad\SymfonyEtaggingBundle\Service\Etagging:
        autoconfigure: true
        autowire: true
    Adsazad\SymfonyEtaggingBundle\Util\EtaggingInterface: '@Adsazad\SymfonyEtaggingBundle\Service\Etagging'

